###############################################################
#     ####         #                               #          # Jobuzzle - Copyright All rights reserved
#     ####         #                               #          #
#       ##  #####  ######  #     # ####### ####### #  #####   # @Author: revers
#       ## #     # #     # #     #      #       #  # #     #  #
#       ## #     # #     # #     #     #       #   # #     #  # @Date:   2015-09-30 12:53:09
#       ## #     # #     # #     #    #       #    # #     #  #
#       ## #     # #     # #     #   #       #     # ######   # @Last Modified by:   revers
#  ####### #     # #     # #     #  #       #      # #        #
#  ######   #####   ######  #####  ####### ####### # #######  # @Last Modified time: 2015-10-28 15:02:40
###############################################################


invokables:
	challengelink_data_fieldset_form : Data/Form/ChallengeLinkDataFieldsetForm
	challengelink_data_create_form : Data/Form/ChallengeLinkDataCreateForm
	challengelink_data_edit_form : Data/Form/ChallengeLinkDataEditForm
	challengelink_data_search_form : Data/Form/ChallengeLinkDataSearchForm